version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - data:/app/data
      - obj:/app/obj
    env_file:
      - .env

volumes:
    data:
    obj:
