version: '3'

services:
    borisbot:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: "borisbot"
        restart: always
        volumes:
            - ./data:/app/data:rw
            - ./logs:/app/logs:rw
        env_file:
            - .env
    qdrant:
        image: qdrant/qdrant
        container_name: "qdrant"
        restart: always
        ports:
            - 6333:6333
        volumes:
            - ./data/qdrant:/qdrant/storage:rw
        env_file:
            - .env
