version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        volumes:
            - ./data:/app/data:rw
            - ./obj:/app/obj:rw
            - ./logs:/app/logs:rw
        env_file:
            - .env
